FROM node:18

ARG NODE_ENV=development

ENV NODE_ENV $NODE_ENV
ENV PORT 8080

EXPOSE $PORT

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY node_module* package.json package-lock.json /opt/app/

RUN npm ci

COPY . .

RUN npm run build

RUN npm install -g nodemon

CMD ["node", "dist/server/index.ts"]
