// Navigate to a category page on framtid.se and run the following command:
// JSON.stringify(Array.from(document.getElementById('category-profession-list').getElementsByTagName('a')).filter(e => e.href.includes('/yrke') && !e.href.includes('lediga-jobb')).map(a => a.innerHTML))

// Administration & ekonomi (https://www.framtid.se/yrken/administration-ekonomi)
const administrationEkonomi = [
  "Administrativ chef",
  "Administratör",
  "Affärsinriktad redovisningsekonom",
  "Agil coach",
  "Aktuarie",
  "Amanuens",
  "Ambassadör",
  "Antagningshandläggare",
  "Apotekschef",
  "Arbetsförmedlare",
  "Arbetsgivare",
  "Arbetsledare",
  "Arbetsledare kyrkogårdsförvaltning",
  "Arbetsmarknadsanalytiker",
  "Arbetsmarknadshandläggare",
  "Arbetsmarknadskonsulent",
  "Arbetsmiljöingenjör",
  "Arbetsmiljöinspektör",
  "Arbetsvägledare",
  "Arkivarie",
  "Autodidakt",
  "Avdelningschef",
  "Banktjänsteman",
  "Bemanningsplanerare",
  "Bemötandeombudsmannen",
  "Besöksbokare",
  "Bibliotekarie",
  "Biblioteksassistent",
  "Bovärd/husvärd",
  "Budgetrådgivare ",
  "Butikskontrollant",
  "Bygglovshandläggare",
  "Campingplatsföreståndare",
  "CEO",
  "CFO",
  "Chef",
  "Chefsassistent",
  "Civilekonom",
  "Controller",
  "CRM-konsult",
  "CV-granskare",
  "Daytrader",
  "Demograf",
  "Departementssekreterare",
  "Designassistent",
  "Diplomat",
  "Distributionsadministratör",
  "Domstolshandläggare",
  "Driftchef",
  "Driftledare",
  "Driftledare-Fastigheter",
  "Ekonom",
  "Ekonomiansvarig",
  "Ekonomiassistent",
  "Ekonomichef",
  "Ekonomihandläggare",
  "Ekonomikommentator",
  "Ekonomiyrken",
  "Enhetschef",
  "Entreprenör / Egenföretagare",
  "EU-ambassadör",
  "EU-jobb",
  "EURES-rådgivare",
  "Europavetare",
  "Expert på cirkulär ekonomi",
  "Extratjänstanställd",
  "Facility manager",
  "Fastighetsansvarig",
  "Fastighetsförvaltare",
  "Fastighetsmäklarassistent",
  "Fastighetsvärd",
  "Finansiell rådgivare",
  "Flyttsamordnare",
  "Folkbokföringshandläggare",
  "Forskarassistent",
  "Forskare",
  "Framtidsforskare",
  "Föreningskonsulent",
  "Företagsledare",
  "Företagsmäklare",
  "Förlagsredaktör",
  "Förrättningsassistent",
  "Försäkringsläkare",
  "Försäkringsmäklare",
  "Försäkringsrådgivare",
  "Försäkringstandläkare",
  "Förvaltningschef",
  "Genealog",
  "Gruppchef",
  "Gymnasiekompetensyrken",
  "Handläggare",
  "Headhunter",
  "HR-administratör",
  "HR-assistent",
  "HR-business partner",
  "HR-partner",
  "HR-specialist",
  "Hälsoekonom",
  "Informationsassistent",
  "Informationschef",
  "Informationsstrateg",
  "Informatör",
  "Inkassohandläggare",
  "Internationell samordnare",
  "Internationell SYV",
  "Intervjuare",
  "Jobbsökarexpert",
  "Kapitalförvaltare",
  "KIP-ingenjör",
  "KMA-samordnare",
  "Kommunchef",
  "Kommunikationschef",
  "Kommunvägledare",
  "Konsulatassistent",
  "Konsult",
  "Kontorsvärd/värdinna",
  "Koordinator",
  "Kronofogde",
  "Kundserviceansvarig",
  "Kundtjänstmedarbetare",
  "Kvalitetsutvecklare",
  "Lagermedarbetare",
  "Logistikchef",
  "Logistikkonsult",
  "Löneadministratör",
  "Löneexpert",
  "Lönekonsult",
  "Lönespecialist",
  "Managementkonsult",
  "Marknadskoordinator",
  "Materialansvarig i landslaget",
  "Medieekonom",
  "Miljö- och hälsoskyddsinspektör",
  "Miljöutredare",
  "Miljövårdsyrken",
  "Multijournalist",
  "Nationalekonom",
  "Nämndsekreterare",
  "Näringslivsutvecklare",
  "Omvärldsanalytiker",
  "Organisationsutvecklare",
  "Pensionsrådgivare",
  "Personaladministratör",
  "Personalansvarig",
  "Personalchef",
  "Personalhandläggare",
  "Personalplanerare",
  "Personalredogörare",
  "Personalsekreterare",
  "Personalspecialist",
  "Personaltjänsteman",
  "Personalvetare",
  "Personlig sekreterare",
  "Politiker",
  "Pressansvarig",
  "Presskommunikatör",
  "Privatekonom",
  "Processledare",
  "Processägare",
  "Produktionsutvecklare",
  "Projektadministratör",
  "Projektassistent",
  "Projektcontroller",
  "Projektekonom",
  "Projekteringsledare",
  "Projektkoordinator",
  "Projektör",
  "Rebrandingexpert",
  "Receptionist",
  "Redovisningsassistent",
  "Redovisningsekonom",
  "Redovisningskonsult",
  "Regionutvecklare",
  "Registrator",
  "Reglerade yrken",
  "Rehabiliteringskoordinator",
  "Reklamombudsman",
  "Rekryterare",
  "Revisor",
  "Revisorsassistent",
  "Riskkapitalist",
  "Rådgivare",
  "Sakkunnig / rådgivare / förhandlare ",
  "Samhällsplanerare",
  "Samhällsutvecklare",
  "Samhällsvetare",
  "Samordnare",
  "Schemaläggare",
  "Sekreterare",
  "Skadereglerare",
  "Skattekonsult",
  "Skatterevisor",
  "Skolforskare",
  "Skolintendent",
  "Skolledare/Rektor",
  "Skrivningsvakt",
  "Socialadministratör",
  "SOS-operatör",
  "Speditör",
  "Stadsbyggnadskoordinator",
  "Statistiker",
  "Statsvetare",
  "Stenograf",
  "Studieförmedlare",
  "Studiestödsutredare ",
  "Sverigechef",
  "Säkerhetschef",
  "Säljare i optikbranschen",
  "Talskrivare",
  "Teamledare",
  "Telefonist",
  "Telefonkommunikatör",
  "Textilekonom",
  "Trainee",
  "Tullinformatör",
  "Undervisningsråd",
  "Underwriter",
  "Upphandlare",
  "Uppräkningspersonal",
  "Urbanplanerare",
  "Utbildningsadministratör",
  "Utbildningshandläggare",
  "Utbildningsjobbare",
  "Uthyrare",
  "Utländsk akademiker",
  "Utredare",
  "Utredare på Försäkringskassan",
  "Utredare på Skatteverket",
  "Utvecklingschef",
  "VerksamhetsIedare/chef",
  "Verksamhetsutvecklare",
  "Verkställande direktör - VD",
  "Vårdadministratör",
  "Värvare",
];

// Bygg & anläggning (https://www.framtid.se/yrken/bygg-anlaggning)
const byggAnlaggning = [
  "Anläggare",
  "Anläggningsarbetare",
  "Anläggningsdykare",
  "Anläggningsprojektör-BIM",
  "Beläggningsarbetare",
  "Bergarbetare",
  "Bergsprängare",
  "Besiktningsman",
  "Betongarbetare",
  "Betongingenjör",
  "Borrtekniker",
  "Broexpert",
  "Bygg- och anläggningsmaskinförare",
  "Byggarbetsledare",
  "Byggchef",
  "Byggledare",
  "Bygglovsprojektör",
  "Byggnadsantikvarie",
  "Byggnadsarbetare",
  "Byggnadskonstruktör",
  "Byggnadsplåtslagare",
  "Byggnadssnickare",
  "Byggproduktionsledare",
  "Byggprojektledare",
  "Byggprojektör",
  "Båtbyggare",
  "Djurstallsplanerare",
  "Elkrafttekniker",
  "Fastighetsutvecklare",
  "Gipstekniker inom bygg",
  "Glas- och metallmontör",
  "Glastekniker / Glasmästare",
  "Golvläggare",
  "Grovarbetare",
  "Håltagare",
  "Ingenjör inom bygg",
  "Kranbilsförare",
  "Kranförare",
  "Linjemålare",
  "Ljusdesigner",
  "Maskinförare",
  "Maskinoperatör",
  "Murare",
  "Målare",
  "Platschef",
  "Platschef inom bygg",
  "Plattsättare",
  "Plåtslagare",
  "Projektmanager inom bygg",
  "Rivningsarbetare",
  "Rörläggare",
  "Samhällsbyggare",
  "Signalvakt",
  "Småhusmontör",
  "Snickare",
  "Stenmontör",
  "Stensättare",
  "Ställningsbyggare",
  "Takläggare",
  "Takmontör",
  "Timmerman",
  "Trafikplanerare",
  "Trappmakare",
  "Träarbetare",
  "Trädgårdsanläggare",
  "Undertaksmontör",
  "Undervattensvetsare",
  "Ventilationsmontör",
  "Verkstadssnickare/maskinsnickare",
];

// Data & IT (https://www.framtid.se/yrken/data-it)
const dataIt = [
  ".NET-utvecklare",
  "3D-grafiker",
  "AI-tränare",
  "Användbarhetsexpert",
  "Applikationsutvecklare",
  "Back-end utvecklare",
  "Cross media producer",
  "Cybersoldat",
  "Cybersäkerhetschef",
  "Cybersäkerhetsspecialist",
  "Databasspecialist/Databasadministratör",
  "Dataingenjör",
  "Dataspelsbranschens yrken",
  "Dataspelsutvecklare",
  "Datasäkerhetsansvarig",
  "Datavetare",
  "DevOps-integrerare",
  "Digital designer",
  "Digital kommunikatör",
  "Drifttekniker inom IT",
  "Embeddedutvecklare",
  "Etisk hackare",
  "Front-end utvecklare",
  "Fullstack-utvecklare",
  "GIS-utvecklare",
  "Hårdvarudesigner",
  "Informationsarkitekt",
  "Ingenjör inom data/elektronik",
  "IT Tekniker / Nätverkstekniker",
  "IT-ansvarig",
  "IT-arkitekt",
  "IT-artist",
  "IT-chef",
  "IT-direktör",
  "IT-forensiker",
  "IT-konsult",
  "IT-molnspecialist",
  "IT-projektledare",
  "IT-specialist",
  "IT-strateg",
  "IT-tekniker",
  "Kvalitetssäkrare/testare inom IT",
  "Leveldesigner",
  "Mjukvarudesigner",
  "Networker",
  "Nätverkstekniker",
  "PHP utvecklare",
  "Produktvisualiserare",
  "Programmerare",
  "SEO-specialist",
  "Supporttekniker",
  "Systemadministratör",
  "Systemarkitekt",
  "Systemintegratör",
  "Systemtekniker",
  "Systemtestare",
  "Systemutvecklare",
  "Säkerhetsarkitekt",
  "Sökmotoroptimerare",
  "UX-designer",
  "VFX-artist",
  "VR-utvecklare",
  "Webbanalytiker",
  "Webbdesigner",
  "Webbproducent",
  "Webbredaktör",
  "Webbutvecklare",
  "Webmaster",
];

// Djursjukvård (https://www.framtid.se/yrken/djurens-sjukvard)
const djurensSjukvard = [
  "Djurambulansförare",
  "Djurfysioterapeut",
  "Djurhälsopersonal",
  "Djurmassör",
  "Djurröntgentekniker",
  "Djursjukskötare",
  "Equiterapeut",
  "Hundpsykolog",
  "Hästodontolog",
  "Hästtandvårdare",
  "Veterinär",
  "Veterinärassistent",
  "Viltjourspersonal",
];

// Fordon & Transport (https://www.framtid.se/yrken/fordon-transport)
const fordonTransport = [
  "Befraktare",
  "Befälhavare på färjor",
  "Bilbärgare",
  "Bilelektriker",
  "Biljettkontrollant i kollektivtrafik",
  "Billackerare",
  "Bilmekaniker",
  "Bilrekonditionerare",
  "Bilrenoverare",
  "Bilskadereparatör",
  "Blomsterbud",
  "Brevbärare",
  "Budbilsförare",
  "Bussförare",
  "Båtman",
  "Chaufför",
  "Cykelbud",
  "Depåchef",
  "Distributionsförare",
  "Fartygsbefäl",
  "Fartygsingenjör",
  "Fjärrbilsförare",
  "Flygbussvärd",
  "Flygledare",
  "Flygmekaniker",
  "Flygplansmontör",
  "Flygplansplåtslagare",
  "Flygplatschef",
  "Flygplatsinspektör",
  "Flygtekniker",
  "Flyttarbetare",
  "Fordonslackerare",
  "Fordonsmekaniker",
  "Fordonstekniker",
  "Fraktassistent inom flyget",
  "Färdtjänstförare",
  "Hamnarbetare",
  "Helikopterpilot",
  "Kabinbesättning",
  "Kontaktledningstekniker",
  "Kryssningsvärd",
  "Lageransvarig",
  "Lagerarbetare",
  "Lagerchef",
  "Lastbils- och maskinmekaniker",
  "Lastbilschaufför / lastbilsförare",
  "Lastbilsmekaniker",
  "Lastmaskinförare",
  "Lokförare",
  "Lots",
  "Maskinmekaniker",
  "Maskinmontör",
  "Matros",
  "Miniubåtskapten",
  "Mobility Manager",
  "Mopedtaxiförare",
  "Motivlackerare",
  "Motorcykelmekaniker",
  "Motorman",
  "Nautiker",
  "Ombordansvarig",
  "Omriktarspecialist",
  "Personbilsmekaniker",
  "Personbilstekniker",
  "Pilot",
  "Pistmaskinsförare",
  "Privatchaufför ",
  "Racingmekaniker",
  "Ramppersonal",
  "Reservdelsansvarig",
  "Servicetekniker",
  "Sjöintendent",
  "Sjökapten",
  "Skrottekniker",
  "Skärgårdskapten",
  "Slussvärd",
  "Sprutlackerare",
  "Spårvagnsförare",
  "Spärrexpeditör / konduktör / trafikvärd",
  "Styrman/båt",
  "Styrman/flygplan",
  "Taxiförare",
  "Tekniskt befäl",
  "Terminalarbetare",
  "Testförare",
  "Tidningsbud",
  "Trafikassistent",
  "Trafikflygare",
  "Trafikinformatör",
  "Trafikingenjör",
  "Trafikledare",
  "Trafikvärd",
  "Traktorförare",
  "Transportledare",
  "Transportplanerare",
  "Truckförare",
  "Tunneltågförare",
  "Tågklarerare",
  "Tågmästare",
  "Tågsamordnare",
  "Tågvärd",
  "Verkstadsmekaniker",
  "Voi hunter",
  "VTS-operatör",
  "Yrkesförare",
];

// Försäljning, inköp & marknad (https://www.framtid.se/yrken/forsaljning-inkop-marknad)
const forsaljningInkopMarknad = [
  "Account manager",
  "Affärsanalytiker",
  "Affärsrådgivare",
  "Affärsutvecklare",
  "Aktiemäklare",
  "Annonssäljare",
  "Antikhandlare",
  "Apoteksassistent",
  "Auktionist",
  "Auktionstjänsteman",
  "Avgiftsförvaltare",
  "B2B säljare",
  "Bensinstationsbiträde",
  "Bilförsäljare",
  "Biografyrken",
  "Brand manager",
  "Branding expert",
  "Bridal consultant",
  "Bröllopskoordinator",
  "Businesskonsult/investerare",
  "Butiksbiträde",
  "Butikschef",
  "Butikskommunikatör",
  "Butiksplockare",
  "Butikssäljare",
  "Båtförsäljare",
  "Centrumledare",
  "Copywriter",
  "Customer Success Manager (CSM)",
  "Demonstratör",
  "Digital marknadsförare",
  "Digital Visual Merchandiser",
  "Diplomerad Gymnasieekonom",
  "Doftexpert",
  "e-Commerce Manager",
  "E-handelslogistiker",
  "Ekonomikonsult",
  "Eventkoordinator",
  "Fastighetsmäklare",
  "Fondförvaltare",
  "Forskare för handeln",
  "Färskvaruansvarig",
  "Företagsekonom",
  "Företagssäljare",
  "Försäkringsförmedlare",
  "Försäljningschef",
  "Glassbilsförare",
  "Grönsakshandlare",
  "Hundmatstestare",
  "Inköpare / Inköpschef",
  "Inköpsassistent",
  "International broker",
  "Internationell säljare",
  "Jordgubbsförsäljare",
  "Kassabiträde, kassapersonal",
  "Knalle",
  "Konsthandlare",
  "Kryptokonsult",
  "Kundmottagare",
  "Lagerplanerare",
  "Lantbruksekonom",
  "Lifestyle manager",
  "Marknadsanalytiker",
  "Marknadsassistent",
  "Marknadschef",
  "Marknadsförare",
  "Marknadskommunikatör",
  "Marknadsundersökare",
  "Mediasäljare",
  "Medierådgivare",
  "Miljöekonom",
  "Mission designer",
  "Mystery shopper",
  "Näringslivsrådgivare",
  "Orderplockare",
  "Personal shopper",
  "Pizzabud",
  "Reklamfilmare",
  "Reklamutdelare",
  "Resesäljare",
  "SEM-specialist",
  "Sherryambassadör",
  "Sportagent",
  "Springvikarie",
  "Styrelseproffs",
  "Säljare",
  "Säljare hos grossist",
  "Säljare i företag",
  "Säljare på Systembolaget",
  "Säljcoach",
  "Teknisk säljare",
  "Telefonförsäljare",
  "Trendanalytiker",
  "Verkmästare på bilverkstad",
  "Visual Merchandiser",
  "Värderare",
];

// Hantverk (https://www.framtid.se/yrken/hantverk)
const hantverk = [
  "Attributmakare",
  "Bilglastekniker",
  "Bilsadelmakare",
  "Bokbindare",
  "Borstbindare",
  "Brodös",
  "Bryggare / bryggeriarbetare",
  "Bössmakare",
  "Ciselör",
  "Dekopör",
  "Dekorationsmålare",
  "Dekormålare",
  "Dekupazist",
  "Dockmakare",
  "Duodji",
  "Emaljerare",
  "Florist",
  "Förgyllare",
  "Gardinmakare",
  "Garvare",
  "Glasarbetare",
  "Glasblåsare",
  "Glasmästare",
  "Glasrestauratör",
  "Gravör",
  "Guldsmed",
  "Gördelmakare",
  "Handskmakare",
  "Hantverkare",
  "Hattmakare",
  "Inredningssadelmakare",
  "Inredningssnickare",
  "Juvelerare",
  "Juvelfattare",
  "Kakelugnsmakare",
  "Kapellmakare",
  "Kemisk förgyllare",
  "Keramiker",
  "Konstgjutare",
  "Konsthantverkare ",
  "Konstinramare",
  "Korgmakare",
  "Kristallkronemakare",
  "Körsnär",
  "Lädergravör",
  "Mattrestauratör",
  "Metallrestauratör",
  "Metalltryckare",
  "Modellsnickare",
  "Modist",
  "Musikinstrumentmakare",
  "Musikinstrumentrestauratör",
  "Målningsrestauratör",
  "Möbelrenoverare",
  "Möbelsnickare",
  "Orgelbyggare",
  "Pappersrestauratör",
  "Patinerare",
  "Perukmakare",
  "Pipmakare",
  "Plymmakare",
  "Pälssömmerska",
  "Repslagare",
  "Sadelmakare",
  "Scenograf",
  "Schatullmakare",
  "Segelmakare",
  "Silversmed",
  "Skeppstimmerman",
  "Skomakare",
  "Skräddare",
  "Skyltmakare",
  "Slipmästare",
  "Smed",
  "Spetsmakare",
  "Stenhuggare",
  "Stickare",
  "Stuckatör",
  "Sömmerska",
  "Tapetmakare",
  "Tapetserare",
  "Taxidermist",
  "Tillskärare",
  "Tryckare",
  "Träbildhuggare",
  "Täljare",
  "Urmakare",
  "Väskmakare",
  "Vävare",
  "Xylograf",
  "Ädelstensslipare",
];

// Hotell, restaurang & turism (https://www.framtid.se/yrken/hotell-restaurang-turism)
const hotellRestaurangTurism = [
  "Affineur",
  "Agent inkommande turism",
  "Allt-i-allo",
  "Bagare",
  "Barchef",
  "Barista",
  "Bartender",
  "Bussresearrangör",
  "Butler",
  "Cafébiträde",
  "Caterer",
  "Charkuterist",
  "Chokladmästare",
  "Cigarrexpert",
  "Concierge",
  "Croupier",
  "Diskare",
  "Dryckesexpert",
  "Evenemangspersonal",
  "Food och beverage manager",
  "Fromager",
  "Front Desk Manager",
  "Frukostvärd / värdinna",
  "Färdigmatlagare",
  "Gastronom",
  "Gatuköksbiträde",
  "Glassmästare",
  "Guide",
  "Hotellchef",
  "Hotellmanager",
  "Hotellreceptionist",
  "Hotellyrken",
  "Hovmästare",
  "Hundspannsguide",
  "Husfru",
  "Kallskänka",
  "Kock",
  "Konditor",
  "Konferensvärdinna / konferensvärd",
  "Kostekonom",
  "Krögare",
  "Köksbiträde",
  "Kökschef",
  "Köksmästare",
  "Lifestyle Concierge",
  "Mathantverkare",
  "Mathistoriker",
  "Matinformatör",
  "Matkritiker",
  "Nattportier",
  "Parkvärd",
  "Patisserist",
  "Peditaxiförare",
  "Pizzabagare",
  "Provsmakare",
  "Resebyråtjänsteman",
  "Reseledare",
  "Reseproducent",
  "Restaurangbiträde",
  "Restaurangchef",
  "Roastmaster",
  "Rotissör",
  "Servitör/Servitris",
  "Skolmåltidsbiträde",
  "Snabbrestaurangbiträde",
  "Sommarjobbare",
  "Sommelier",
  "Specialbagare",
  "Språkresearrangör",
  "Storköksbiträde",
  "Turistchef",
  "Turistinformatör",
  "Tårtmakare",
  "Utklädd",
  "Viltslaktare",
  "Whiskeykännare",
  "Ystare",
  "Äventyrare",
  "Äventyrsguide",
];

// Hälsa & sjukvård (https://www.framtid.se/yrken/halsa-sjukvard)
const halsaSjukvard = [
  "Akupunktör",
  "Akutsjuksköterska",
  "Alkohol- och drogterapeut",
  "Allergikonsulent",
  "Ambulanssjuksköterska",
  "Ambulanssjukvårdare",
  "Anaplastolog / Ansiktsprotetiker",
  "Anestesisjuksköterska",
  "Apotekare",
  "Apotekstekniker",
  "Arbetsterapeut",
  "Arbetsterapibiträde",
  "Audionom",
  "Bariatriker",
  "Barnläkare",
  "Barnmorska",
  "Barnsjuksköterska",
  "Barnsömnspecialist",
  "Beroendeterapeut",
  "Biomedicinsk analytiker",
  "Boendestödjare / boendeassistent",
  "Chefssjuksköterska",
  "Dermatolog",
  "Diabetessjuksköterska",
  "Dietist",
  "Distriktsläkare",
  "Distriktssköterska",
  "DNA-coach",
  "Doula",
  "Embryolog",
  "Farmaceut",
  "Fitnessinstruktör",
  "Flygläkare",
  "Folkhälsoplanerare",
  "Folkhälsosamordnare",
  "Friskvårdskonsulent",
  "Friskvårdsterapeut",
  "Fysioterapeut",
  "Fytoterapeut",
  "Företagssköterska",
  "Geriatriksjuksköterska",
  "Gipstekniker inom sjukvården",
  "Gym-personal",
  "Gyminstruktör",
  "Gynekolog",
  "Habiliteringsassistent",
  "Habiliteringspersonal",
  "Hematolog",
  "Hemtjänstpersonal",
  "Hjälpmedelskonsulent",
  "Hjälpmedelstekniker",
  "Homeopat ",
  "Hälso- och sjukvårdsinspektör",
  "Hälsoinformatör",
  "Hälsopedagog",
  "Idrottsmassör",
  "Idrottsmedicinare",
  "Intensivvårdssjuksköterska",
  "Kardiolog",
  "Kiropraktor",
  "Kirurg",
  "Konstterapeut",
  "Kostrådgivare",
  "Kostvetare",
  "Legitimationsyrken",
  "Logoped",
  "Läkare",
  "Läkarsekreterare",
  "Medical detection utvecklare",
  "Medicinsk genetiker",
  "Medicinsk make up artist",
  "Medicinsk sekreterare",
  "Medicinsk tränare",
  "Medicinteknisk ingenjör",
  "Miljöpsykolog",
  "Musikterapeut",
  "Naprapat",
  "Neonatalläkare",
  "Nutritionist",
  "Obduktionstekniker",
  "Oftalmolog",
  "Okularist",
  "Omsorgsassistent",
  "Onkolog",
  "Onkologisjuksköterska",
  "Operationssjuksköterska",
  "Optiker",
  "Optikerassistent",
  "Ortopedingenjör",
  "Ortopedtekniker",
  "Ortoptist",
  "Osteopat",
  "Pacemakersjuksköterska",
  "Patolog",
  "Pedodontist",
  "Peer supporter",
  "Perfusionist",
  "Personlig assistent",
  "Personlig Tränare, PT",
  "Podiater",
  "Psykiatriker",
  "Psykiatrisjuksköterska",
  "Psykolog",
  "Psykoterapeut",
  "PTP-psykolog",
  "Radiolog",
  "Receptarie",
  "Rehabassistent",
  "Röntgensjuksköterska",
  "Sektionschef inom vården",
  "Servicemedarbetare inom sjukvården",
  "Sjukhusclown",
  "Sjukhusfysiker",
  "Sjukhustransportör",
  "Sjukhusyrken",
  "Sjuksköterska",
  "Sjuksköterska inom digital vård",
  "Sjuksköterska inom psykiatri",
  "Sjuksköterska inom äldrevård",
  "Sjuksköterska, medicin och kirurgi",
  "Sjukvårdsrådgivare ",
  "Skolsköterska",
  "Skötare inom psykiatrisk vård",
  "Sonograf",
  "Specialistläkare",
  "Specialistsjuksköterska",
  "Specialisttandläkare",
  "Specialistundersköterska",
  "Specialistundersköterska med neuropsykiatrikompetens",
  "ST-läkare",
  "Steriltekniker",
  "Sårsjuksköterska",
  "Sömncoach",
  "Tandhygienist",
  "Tandläkare",
  "Tandsköterska",
  "Tandtekniker",
  "Transplantationskoordinator",
  "Tuberkulos-expert",
  "Undersköterska",
  "Uroterapeut",
  "Vattengympainstruktör",
  "Vårdbiträde",
  "Yrkeshygieniker",
  "Återhämtningsterapeut",
  "Ögonsjuksköterska",
];

// Industri (https://www.framtid.se/yrken/industri)
const industri = [
  "CNC-fräsare",
  "Efterbearbetare inom pappersindustrin",
  "Elektronikmontör",
  "Förpackningsarbetare",
  "Grovplåtslagare",
  "Gruvarbetare",
  "Handpaketerare",
  "Industrisömmerska",
  "Ingenjör inom stål- och metallindustrin",
  "Operatör",
  "Processoperatör",
  "Processoperatör inom livsmedelsindustrin",
  "Processoperatör stål och metallindustri",
  "Slaktare",
  "Styckare",
  "Svarvare",
  "Svetsare",
  "Verkstadsarbetare",
  "Verkstadsplåtslagare",
  "Virkesmätare",
  "Ytbehandlare",
];

// Installation, drift & underhåll (https://www.framtid.se/yrken/installation-drift-underhall)
const installationDriftUnderhall = [
  "Automationsmontör",
  "Automationstekniker",
  "Bangårdsoperatör",
  "Bantekniker",
  "Beredare",
  "CNC-operatör",
  "Cykelreparatör / cykelmekaniker",
  "Distributionselektriker",
  "Driftoptimerare",
  "Drifttekniker",
  "Drifttekniker inom Fastighet",
  "Däckmontör",
  "Elmontör",
  "Elnätsspecialist",
  "Eltekniker",
  "Fastighetsskötare",
  "Fastighetstekniker",
  "Fastighetsyrken",
  "Finmekaniker",
  "Fordonsmontör",
  "Formmaskinoperatör inom plastindustrin",
  "Gjutare",
  "Greenkeeper",
  "Hissmontör",
  "Idrottsplatsarbetare",
  "Industriell klättrare",
  "Industrilackerare",
  "Industrirörmontör",
  "Installations- och serviceelektriker",
  "Installationsingenjör",
  "Installationsledare",
  "Isolerare",
  "Järnvägstekniker",
  "Kaffetekniker",
  "Kantpressare",
  "Kommunikationselektriker",
  "Kontorsmaskinreparatör",
  "Kontorsvaktmästare",
  "Kyl- och värmepumptekniker",
  "Kylmaskinist",
  "Kylmontör",
  "Kyrkvaktmästare",
  "Larminstallatör / larmtekniker",
  "Liftskötare / lifttekniker",
  "Ljudtekniker",
  "Låssmed",
  "Maskinpersonal",
  "Maskinreparatör",
  "Maskinställare",
  "Mekaniker",
  "Montör",
  "Områdestekniker",
  "Pianotekniker",
  "Poolskötare",
  "Produktionstekniker",
  "Reliningstekniker",
  "Reläskyddsspecialist",
  "Reparatör-lok och vagn",
  "Riggare",
  "Rörmokare",
  "Rörnätstekniker",
  "Servicetekniker Elkraft",
  "Signaltekniker",
  "Snöröjare",
  "Sprinklermontör",
  "Spårsvetsare",
  "Teknisk förvaltare",
  "Teletekniker",
  "Truckreparatör",
  "Underhållsmontör",
  "Underhållstekniker",
  "VA-Läcksökare",
  "Vaktmästare",
  "Vatten- och miljötekniker",
  "Vattenkrafttekniker",
  "Ventilationsingenjör",
  "Ventilationsisolerare",
  "Verkstadstekniker",
  "Vitvarureparatör",
  "VVS-ingenjör",
  "VVS-installatör",
  "VVS-montör",
  "VVS-tekniker",
  "Vägarbetare",
  "Yrkessvetsare - IW",
];

// Juridik (https://www.framtid.se/yrken/juridik)
const juridik = [
  "Advokat",
  "Advokatsekreterare",
  "Affärsjurist",
  "Allmänhetens Pressombudsman",
  "Barn- och elevombudet",
  "Barnombudsman",
  "Beslutsfattare på Migrationsverket",
  "DO (Diskrimineringsombudsman)",
  "Domare",
  "Domstolsyrken",
  "EU-kommissionär",
  "Facklig förtroendeman",
  "Fiskal",
  "Företagsjurist",
  "Internationell rättsvetare",
  "IP-konsult",
  "IP-paralegal",
  "Jurist",
  "Jämställdhetssamordnare",
  "Konkursförvaltare",
  "Konsumentvägledare",
  "Kronoinspektör",
  "Licensexpert",
  "Markförhandlare",
  "Notarie",
  "Ombudsman",
  "Paralegal",
  "Patentingenjör",
  "Patentombud",
  "Rättsvetare",
  "Verksjurist",
  "Åklagare",
];

// Kropps- & skönhetsvård (https://www.framtid.se/yrken/kropps-skonhetsvard)
const kroppsSkonhetsvard = [
  "Badmästare",
  "Barberare",
  "Ergonom",
  "Estetisk injicerare",
  "Frisör",
  "Hudterapeut",
  "Idrottsnutritionist",
  "Kosmetolog",
  "Laserterapeut",
  "Manikyrist och nagelterapeut",
  "Massör",
  "Medicinsk fotterapeut",
  "Militaryfitness instruktör",
  "Mindfulnessinstruktör",
  "Nagelspecialist",
  "Piercare",
  "Plastikkirurg",
  "SPA-medarbetare",
  "SPA-terapeut",
  "Stylist",
  "Tatuerare",
  "Vaxare",
  "Yogainstruktör",
];

// Kultur, media & design (https://www.framtid.se/yrken/kultur-media-design)
const kulturMediaDesign = [
  "3D-printgrafiker",
  "Ackompanjatör",
  "AD-assistent",
  "Animatör",
  "Antikvarie",
  "Arkitektyrken",
  "Art director",
  "Artist",
  "Artistagent/manager",
  "Artistbokare",
  "Assistent inom filmbranschen",
  "Astrolog",
  "Ateljerista",
  "Auktionsintendent",
  "B-fotograf",
  "BH-specialist",
  "Bildbehandlare",
  "Bildingenjör",
  "Bildkonstnär",
  "Bloggare",
  "Bokförlagsyrken",
  "Bowlinghallsbiträde",
  "Bröllopsfotograf",
  "Byakorre",
  "C-fotograf",
  "Cirkusartist",
  "Cirkusyrken",
  "Content manager",
  "Creative director - CD",
  "Curator",
  "Dansare",
  "Danssportare",
  "Dataspelare",
  "Dekoratör",
  "Designer",
  "Designer inom mode och textil",
  "Designmodellör",
  "Digital Imaging Technician",
  "Digitaltryckare",
  "Direktris",
  "Dirigent",
  "Discjockey - DJ",
  "Dockförare ",
  "Dubbelgångare",
  "Dövblindtolk",
  "Efterbehandlare",
  "Etikettexpert",
  "Etisk konstförfalskare ",
  "Etnolog",
  "EU-tolk",
  "Event-yrken",
  "Eventarrangör",
  "Eventdekoratör",
  "Eventtekniker",
  "FAD",
  "Filmfotograf",
  "Filmklippare",
  "Filmkompositör",
  "Filmkritiker",
  "Filmrecensent",
  "Filmregissör",
  "Filmvetare",
  "Filmyrken",
  "Flexotryckare",
  "Folkvettsexpert ",
  "Fotbollsdomare",
  "Fotograf",
  "Färgnyanserare",
  "Föreläsare",
  "Författare",
  "Förpackningsgrafiker",
  "Gallerist",
  "Garment technical designer",
  "Gatuartist",
  "Gatuporträttist",
  "Gemmolog",
  "Giggare",
  "Globetrotter",
  "Golfcaddie",
  "Graffitiexpert",
  "Grafiker",
  "Grafisk designer",
  "Grafisk formgivare",
  "Grafisk produktionsledare",
  "Hemslöjdskonsulent",
  "Hobby",
  "Hologramutvecklare",
  "Hotel entertainer",
  "Humanist",
  "Idrottsscout",
  "Illustratör",
  "Image-konsult",
  "Influencer",
  "Inredare",
  "Inredningsarkitekt",
  "Inredningsdesigner",
  "Inrikespolitisk kommentator",
  "Inspicient",
  "Isskulptör",
  "Journalist / Reporter",
  "Jultomte",
  "Kalaskoordinator",
  "Kalligraf",
  "Klädesdesigner",
  "Kommunikatör",
  "Konferencier",
  "Konservator",
  "Konstdetektiv",
  "Konstmodell",
  "Konstmålare",
  "Konstnär",
  "Konstnärlig ledare",
  "Konstvetare",
  "Koreograf",
  "Korrekturläsare",
  "Korsordskonstruktör",
  "Kostymör",
  "Kroppsmålare",
  "Krönikör",
  "Kulturarvspedagog",
  "Kulturattaché",
  "Kulturförmedlare",
  "Kulturinformatör",
  "Kulturkommunikatör",
  "Kulturkonsulent",
  "Kulturkritiker",
  "Kulturproducent",
  "Kulturvetare",
  "Kyrkomusiker / Kantor",
  "Köksdesigner",
  "Lasershow-tekniker",
  "Lektör ",
  "Lekvärd",
  "Levande seriefigur",
  "Levnadstecknare",
  "Ljudboksinläsare",
  "Ljussättare",
  "Låtskrivare",
  "Magiker",
  "Manusförfattare",
  "Maskör",
  "Mediaplanerare",
  "Medietränare",
  "Miniatyrmakare",
  "Modedesigner",
  "Modell och mannekäng",
  "Moderedaktör",
  "Modevetare",
  "Monterexpert/mässgeneral",
  "Museitjänsteman",
  "Musiker",
  "Musikproducent",
  "Mönsterkonstruktionsassistent",
  "Mönsterkonstruktör",
  "Naturfotograf",
  "Offsettryckare",
  "Origamimästare",
  "Originalare",
  "Pagentcoach",
  "Passare",
  "Platsletare",
  "Poddare",
  "Poet",
  "Pokerproffs",
  "Politisk redaktör",
  "Postproduktionskoordinator",
  "PR-agent",
  "PR-konsult",
  "Prepressgrafiker",
  "Pressfotograf ",
  "Producent",
  "Producent av text för syntolkning",
  "Produktionsledare inom film och reklam",
  "Professionell idrottsutövare",
  "Programchef",
  "Programledare",
  "Påklädare",
  "Radio- och TV-tekniker",
  "Radiopratare",
  "Redigerare",
  "Regissör",
  "Rekvisitör och attributör",
  "Resejournalist",
  "Retoriker",
  "Röstskådespelare",
  "SAD",
  "Samhälls- och kulturanalytiker",
  "Scripta",
  "Skolfotograf",
  "Skribent",
  "Skådespelare",
  "Sminkör, Make Up artist",
  "Smyckesdesigner",
  "Social media manager",
  "Sportkommentator",
  "Sportvideoanalytiker",
  "Språkteknolog",
  "Språkvetare",
  "Språkvårdare",
  "Språkyrken",
  "Staging designer",
  "Statist",
  "Storbildsproducent",
  "Storyboard artist",
  "Studioman",
  "Stuntman",
  "Stå-upp komiker",
  "Sufflör",
  "Syntolk",
  "Sångare",
  "Teckenspråkstolk",
  "Tecknare",
  "Tivoliarbetare",
  "Tolk",
  "Tonsättare",
  "Trampare",
  "TV-producent ",
  "Uniformsutvecklare",
  "Utrikeskommentator",
  "Utrikeskorrespondent",
  "Utställningsproducent",
  "Varietéartist ",
  "Videoreporter",
  "Visualiserare",
  "Visuell grafisk kommunikatör",
  "Växtinredare",
  "YouTuber",
  "Översättare",
];

// Naturbruk (https://www.framtid.se/yrken/naturbruk)
const naturbruk = [
  "Agilitylärare",
  "Agronom",
  "Agrotekniker",
  "Arborist",
  "Avbytare",
  "Beridare",
  "Biodlare/biskötare",
  "Biogastekniker",
  "Bärodlare",
  "Bärplockare",
  "Djurkommunikatör",
  "Djurskyddsinspektör",
  "Djurskötare inom lantbruk",
  "Djurtränare",
  "Djuruppfödare",
  "Djurvårdare / djurskötare",
  "Djurvårdare vid djurpark",
  "Dogwalker",
  "Driftledare-jordbruk",
  "Entreprenör i det gröna näringslivet",
  "Etolog",
  "Fiskare",
  "Fiskekontrollant",
  "Fiskevårdare",
  "Fiskodlare",
  "Fruktodlare",
  "Fågelskrämmare",
  "Fårklippare",
  "Förädlingsassistent",
  "Gårdsbutiksföretagare",
  "Gårdsmästare",
  "Hortonom",
  "Hovslagare",
  "Hundbeteendevetare",
  "Hunddagisföretagare",
  "Hundfriskvårdare",
  "Hundförare",
  "Hundyrken",
  "Husdjursagronom",
  "Husdjurstekniker",
  "Husdjursvetare",
  "Hästskötare",
  "Hästtränare",
  "Hästuppfödare",
  "Hästviskare",
  "Hästyrken",
  "Jaktvårdskonsulent",
  "Jockey",
  "Jägmästare",
  "Kamelskötare",
  "Kattbeteendevetare",
  "Kennelägare",
  "Klimatanpassningssamordnare",
  "Klövvårdare",
  "Kusk",
  "Lantbrukare",
  "Lantmästare",
  "Maskinförare inom lantbruk",
  "Miljöinspektör",
  "Miljökonsult",
  "Mjölkbonde",
  "Naturbevakare",
  "Naturguide",
  "Naturinformatör",
  "Naturvårdare",
  "Naturvårdsbiolog",
  "Park ranger",
  "Parkarbetare",
  "Pet Groomer",
  "Plantskoleföretagare",
  "Platschef i skogsindustri",
  "Renskötare",
  "Reptilskötare",
  "Skogliga yrken",
  "Skogsarbetare",
  "Skogsavverkare",
  "Skogsbrukstekniker",
  "Skogsförvaltare",
  "Skogsinspektör",
  "Skogskonsulent",
  "Skogsmaskinförare",
  "Skogsmästare",
  "Skogsplanerare",
  "Skogsplanterare",
  "Skogsröjare",
  "Skogstekniker",
  "Skogsvårdsarbetare",
  "Snigelfarmare",
  "Sportfiskeguide",
  "Stallarbetare",
  "Sågverksoperatör",
  "Traktormekaniker",
  "Travtränare",
  "Trädfällare",
  "Trädgårdsarbetare",
  "Trädgårdsarkitekt",
  "Trädgårdsdesigner",
  "Trädgårdsingenjör",
  "Trädgårdsmästare",
  "Trädgårdsrådgivare/ trädgårdskonsulent",
  "Vatten- och avloppsprojektör",
  "Viltförvaltare",
  "Viltmästare",
  "Viltvårdare",
  "Vinodlare / vinproducent",
  "Växthusgrönsaksodlare",
  "Växtodlare",
  "Växtskötare",
  "Zoohandlare",
  "Zoolog vid djurpark",
];

// Naturvetenskapligt arbete (https://www.framtid.se/yrken/naturvetenskapligt-arbete)
const naturvetenskapligtArbete = [
  "Analytisk kemist",
  "Antropolog",
  "Arkeolog",
  "Astrobiolog",
  "Astrofysiker",
  "Astronaut",
  "Astronom",
  "Atmosfärskemist",
  "Audiolog",
  "Balsamerare",
  "Bioarkeolog",
  "Biohackare",
  "Biokemist",
  "Biolog",
  "Biomedicinare",
  "Biomedicinsk analytiker inom fysiologi",
  "Biomedicinsk analytiker med inriktning labmedicin",
  "Biostatistiker",
  "Bioteknolog",
  "Botaniker",
  "Civilingenjör i kemiteknik",
  "Cytodiagnostiker",
  "Dendrikronolog",
  "Ekolog",
  "Ekorådgivare",
  "Entomolog",
  "Epidemiolog",
  "Epidemiologiassistent",
  "Etnograf",
  "Evolutionsbiolog",
  "Farmakolog",
  "Fingeravtrycksanalytiker",
  "Forensiker",
  "Forskare inom bioteknik",
  "Forskare med inriktning mot metabolomik",
  "Forskningsassistent",
  "Forskningsdjurvårdare",
  "Forskningsingenjör",
  "Fysiker",
  "Förvaltare för länets nationalpark eller naturreservat ",
  "Genetiker",
  "Geograf",
  "Geoingenjör",
  "Geolog",
  "Geotekniker",
  "Geovetaryrken",
  "Glaciolog",
  "Grafolog",
  "Grottdykare",
  "Hippolog",
  "Hydrogeolog",
  "Hydrolog",
  "Immunolog",
  "Infektionist",
  "Kemist",
  "Kognitiv zoolog",
  "Kosmolog",
  "Kultur/naturgeograf",
  "Laboratorieassistent",
  "Laboratorieingenjör inom kemiområdet",
  "Life science yrken",
  "Limnolog",
  "Livsmedelsinspektör",
  "Läkemedelskemist",
  "Läkemedelstekniker",
  "Läkemedelsutvecklare",
  "Marinbiolog",
  "Meteorolog",
  "Miljöfarmakolog",
  "Miljöhygieniker",
  "Miljöingenjör",
  "Miljökemist ",
  "Miljökoordinator",
  "Miljöplanerare",
  "Miljövetare",
  "Molekylärbiolog",
  "Mykolog",
  "Måltidsekolog",
  "Mögelexpert",
  "Naturvetare",
  "Naturvägledare",
  "Neurobiolog",
  "Neurolog",
  "Nutritionsepidemiolog",
  "Oceanograf",
  "Ornitolog",
  "Osteoarkeolog",
  "Osteolog",
  "Paleogenetiker",
  "Paleontolog",
  "Paleopatolog",
  "Palynolog",
  "Planetolog",
  "Rymdfysiker",
  "Rymdyrken",
  "Rättsantropolog",
  "Rättsläkare",
  "Samhällsbiolog",
  "Samhällsgeograf",
  "Seismolog ",
  "Skogsforskare",
  "Socialantropolog",
  "Toxikolog/Ekotoxikolog",
  "Vattenekolog",
  "Vattenstrateg",
  "Viltpatolog",
  "Vulkanolog",
  "Växtfysiolog",
  "Växtgenetiker",
  "Zoolog",
];

// Pedagogiskt arbete (https://www.framtid.se/yrken/pedagogiskt-arbete)
const pedagogisktArbete = [
  "Adjunkt",
  "Akademiker",
  "APL-utvecklare",
  "Astronomilärare",
  "Au Pair",
  "Barnskötare",
  "Barnvakt",
  "Beteendestrateg",
  "Bildlärare",
  "Cirkelledare",
  "Danslärare/danspedagog",
  "Datautbildare",
  "Doktorand",
  "Dramapedagog",
  "Dykinstruktör",
  "Elevassistent",
  "Enneagramkonsult",
  "Expert",
  "Folkhögskolelärare",
  "Fritidscoach",
  "Fritidsföreståndare",
  "Fritidspedagog",
  "Församlingspedagog",
  "Förskolechef/Rektor",
  "Förskollärare",
  "Förstelärare",
  "Föräldracoach",
  "Genusvetare",
  "Grundskollärare",
  "Gymnasiestrateg",
  "Handledare",
  "Handledare i lovskolan",
  "Hantverkspedagog",
  "Hem- och konsumentkunskapslärare",
  "Historielärare",
  "Historiker",
  "Holistisk coach",
  "Hundcoach",
  "Hundskötare",
  "Hälsorådgivare",
  "Hästunderstödd terapeut",
  "Högskolelärare",
  "Hörselassistent",
  "IB-koordinator",
  "Idrottskonsulent",
  "Idrottslärare",
  "Idrottstränare",
  "Idrottsvetare",
  "IKT-pedagog",
  "Integrationspedagog",
  "IT-lärare",
  "Jobbcoach",
  "Juniorlärare",
  "Karriärcoach",
  "Kickass-coach",
  "Kolloledare",
  "Kompetensmäklare",
  "Kulturgeograf",
  "Kulturskolepedagog",
  "Lekterapeut",
  "Lingvist",
  "Livscoach",
  "Logonom",
  "Lärarassistent",
  "Lärare",
  "Lärare i anpassad skola",
  "Lärare i fritidshem",
  "Lärare i förskoleklass och årskurs 1-3",
  "Lärare i kommunikation",
  "Lärare i vissa ämnen",
  "Läshundförare",
  "Läxhjälpare",
  "Medicinhistoriker",
  "Mental coach",
  "Modersmålslärare",
  "Motivationscoach",
  "Motivationspedagog",
  "Museipedagog",
  "Musiklärare",
  "Måltidsforskare",
  "Pedagog",
  "Pedagogista",
  "Praktiksamordnare",
  "Professor",
  "Psykologilärare",
  "Psykologisk coach",
  "Relationscoach",
  "Ridlärare, ridinstruktör",
  "Samhällsvägledare",
  "Sexolog",
  "SFI-lärare",
  "Simlärare",
  "SIUS-konsulent",
  "Sjukhuslärare",
  "Självförsvarsinstruktör",
  "Skidlärare",
  "Skolbibliotekarie",
  "Snickerista",
  "Social brobyggare",
  "Sociologilärare",
  "Specialistofficer",
  "Speciallärare",
  "Specialpedagog",
  "Språkkonsult",
  "Språkledare",
  "Språklärare",
  "Studie- och yrkesvägledare, SYV",
  "Studiecoach",
  "Studiehandledare",
  "Studiepedagog",
  "Stödpedagog",
  "Syn- och hörselinstruktör",
  "Sångpedagog",
  "Teknikutvecklingschef",
  "Teolog",
  "Terminolog",
  "Textilslöjdslärare",
  "Trafikinspektör",
  "Trafiklärare",
  "Trä- och metallslöjdlärare",
  "Undervisningslogistiker",
  "Ungdomscoach",
  "Ungdomskonsulent",
  "Upplevelsedesigner",
  "Utbildare",
  "Utbildningsinformatör",
  "Utbildningskonsult",
  "Utbildningsmäklare",
  "Utmattningsterapeut",
  "Utomhuspedagog",
  "Vetenskapskommunikatör med rymdinriktning",
  "Vetenskapskommunikatör med zooinriktning",
  "Visualiseringscoach",
  "Vuxenlärare",
  "Waldorflärare",
  "Yrkeslärare",
  "Ämneslärare",
];

// Sanering & renhållning (https://www.framtid.se/yrken/sanering-renhallning)
const saneringRenhallning = [
  "Asbestsanerare",
  "Fönsterputsare",
  "Gatustädare",
  "Hotellstädpersonal",
  "Kemdykare",
  "Kemtvättare",
  "Lokalvårdare",
  "Miljövärd",
  "Organizer",
  "Ormsanerare",
  "Renhållningsarbetare",
  "Saneringsarbetare",
  "Skadedjurstekniker",
  "Skorstensfejare, sotare",
  "Städare",
  "Städspecialist",
  "Tvätteriarbetare",
  "Tvättpersonal/garagearbetare",
  "Återvinningsarbetare",
];

// Socialt arbete (https://www.framtid.se/yrken/socialt-arbete)
const socialtArbete = [
  "Adoptionshandläggare",
  "Aktiveringspedagog",
  "Aktivitetsinspiratör",
  "Begravningsentreprenör",
  "Begravningsrådgivare",
  "Behandlingsassistent",
  "Behandlingspedagog",
  "Beteendevetare",
  "Biståndsarbetare",
  "Biståndsbedömare / Biståndshandläggare",
  "Boendekoordinator",
  "Dagbarnvårdare",
  "Diakon",
  "Drogförebyggare",
  "Enhetschef inom social omsorg",
  "Etableringslots",
  "Etikexpert",
  "Extrajobb",
  "Familjebehandlare",
  "Familjehemsförälder",
  "Familjehemssekreterare",
  "Familjerådgivare",
  "Familjerättssekreterare",
  "Filosof",
  "Forensisk socialutredare",
  "Fritidsledare",
  "Frivårdsinspektör",
  "Fältarbetare",
  "God man",
  "Handledare i sorgbearbetning",
  "Hemfixare",
  "Hälso- och sjukvårdskurator",
  "Integrationsvägledare",
  "IT-guide",
  "KAA-ansvarig",
  "Kontaktperson",
  "Kontakttolk",
  "Kriminalvårdsinspektör",
  "Kurator",
  "Kvalitets- och etikrådgivare",
  "Kvinnojoursmedarbetare",
  "Kyrkogårdsföreståndare",
  "Ledsagare",
  "LSS-handläggare",
  "Lyckoforskare",
  "Matchmaker",
  "Medium",
  "Medlare",
  "Pastor",
  "Personligt ombud",
  "Projektledare",
  "Präst",
  "Riksförbundsmedarbetare",
  "Romantiska yrken",
  "Sakkunnig krisstöd",
  "Samlevnadsexpert",
  "Samtalsterapeut",
  "Servicekontorsmedarbetare",
  "Skolkurator",
  "Skolvärd/skolvärdinna",
  "Skrivtolk",
  "Social entreprenör",
  "Social hållbarhetsstrateg",
  "Socialpedagog",
  "Socialsekreterare",
  "Sociolog",
  "Socionom",
  "Socionomyrken",
  "Stödassistent",
  "Störningsjourspersonal",
  "Synrehabiliterare",
  "Trygghetsvärd",
  "Volontär",
  "Vårdare inom funktionsvariation",
];

// Säkerhetsarbete (https://www.framtid.se/yrken/sakerhetsarbete)
const sakerhetsarbete = [
  "Arrestantvakt",
  "Babyproof-expert",
  "Badvakt",
  "Ballistiker",
  "Beredskapssamordnare",
  "Bergsguide",
  "Besiktningstekniker",
  "Bombtekniker",
  "Bostadsvakt",
  "Brandingenjör",
  "Brandinspektör",
  "Brandman",
  "Brandtekniker",
  "Brandteknisk utredare",
  "Brottsförebyggande samordnare",
  "Brottsplatsundersökare",
  "Civil utredare",
  "Civil väktare",
  "Deltidsbrandman",
  "Fallskärmsjägare",
  "Farliga yrken",
  "Fjällräddare",
  "Flygingenjör",
  "Flygplatsbrandman",
  "Flygplatskontrollant",
  "Flygtekniker inom försvarsmakten",
  "FN-jobb",
  "Forensisk accountant",
  "Förrådsman",
  "Försvarsattaché",
  "Godsspanare",
  "Gränskontrollant",
  "Helikopterpilot inom försvarsmakten",
  "Hundförare i Försvarsmakten",
  "Hundförare/väktare",
  "Instruktör i krisberedskap",
  "Integrationspolis",
  "Klienthandläggare",
  "Kriminaltekniker",
  "Kriminalvårdare",
  "Kriminolog",
  "Kustbevakningstjänsteman",
  "Larmoperatör",
  "Lavintekniker",
  "Livvakt",
  "Militärpolis",
  "Militärtolk",
  "Mordutredare",
  "Officersyrken",
  "Ordningsvakt",
  "Parkeringsvakt",
  "Polis",
  "Polisfotograf",
  "Polishundförare",
  "Polisyrken",
  "Poollivräddare",
  "Privatdetektiv",
  "Provförrättare",
  "Provskjutare",
  "Publikvärd",
  "Reservofficer",
  "Ridande polis",
  "Riskhanterare",
  "Räddningsdykare",
  "Räddningsledare",
  "Rättssociolog",
  "Röjdykare",
  "Rökdykare",
  "Sambandsofficer",
  "Scenarbetare",
  "Securityinspektör",
  "Skyddsvakt",
  "Soldat",
  "Sprängämneshundförare",
  "Stridspilot",
  "Säkerhetskoordinator",
  "Säkerhetspolis",
  "Säkerhetsskyddstekniker",
  "Säkerhetsstrateg",
  "Säkerhetstekniker",
  "Terrorexpert",
  "Transportflygpilot",
  "Trygghetskonsulent",
  "Trygghetsoperatör",
  "Tulltjänsteman",
  "Utryckningspolis",
  "Vapentekniker",
  "Väktare",
  "Värdetransportör",
  "Yrkesinformatör inom Försvarsmakten",
  "Yrkesofficer",
  "Ytbärgare",
];

// Tekniskt arbete (https://www.framtid.se/yrken/tekniskt-arbete)
const teknisktArbete = [
  "3D-Laser operatör",
  "3D-skanningstekniker",
  "3D-tekniker",
  "3D-yrken",
  "Akustiker",
  "Akvarietekniker",
  "Anbudsingenjör",
  "Anläggningsingenjör",
  "Anläggningsmontör Storkraftnät",
  "Arbetsingenjör",
  "Arkitekt",
  "Automationselektriker",
  "Automationsingenjör",
  "AV-Tekniker",
  "Baxare",
  "Bildesigner",
  "Biotekniker",
  "Byggnadsingenjör",
  "Byggprojektör CAD/BIM",
  "CAD-konstruktör",
  "Civilingenjör",
  "Civilingenjör i datateknik",
  "Civilingenjör i maskinteknik",
  "Civilingenjör inom bioteknik",
  "Civilingenjör inom Farkostteknik",
  "CNC-svarvare",
  "CNC-tekniker",
  "Designingenjör",
  "Driftingenjör",
  "Drifttekniker i processindustri",
  "Drönarpilot",
  "Ekoingenjör",
  "Elektriker",
  "Elingenjör",
  "Elkonstruktör",
  "Elkraftsingenjör",
  "Energiingenjör",
  "Energioptimerare",
  "Energistrateg",
  "Energitekniker",
  "Fartygselektriker",
  "Fastighetsingenjör",
  "Fibersvetsare",
  "Flygplanselektriker",
  "Fukttekniker",
  "Förpackningstekniker",
  "Gatuingenjör",
  "GIS-ingenjör",
  "Gjuteritekniker",
  "Grafisk automationstekniker ",
  "Gummitekniker",
  "Gymnasieingenjör",
  "Helikoptertekniker",
  "Hydraulikkonstruktör",
  "Hydraultekniker",
  "Hyveloperatör",
  "Högskoleingenjör",
  "Industridesigner",
  "Industrielektriker",
  "Ingenjör",
  "Ingenjör i elektroteknik",
  "Ingenjör inom maskinteknik",
  "Innovationsteknolog",
  "Innovatör",
  "Interaktionsdesigner",
  "Järnvägsprojektör",
  "Kabelnätsdesigner",
  "Kalkylator",
  "Kartingenjör och karttekniker",
  "Kemiingenjör",
  "Komposittekniker",
  "Krematoriemedarbetare",
  "Landskapsarkitekt",
  "Landskapsingenjör",
  "Lantmätare",
  "Livsmedelsingenjör",
  "Livsmedelstekniker",
  "Ljustekniker",
  "Logistiker",
  "Logistikingenjör",
  "Marintekniker",
  "Maskiningenjör",
  "Maskinspecialist",
  "Maskintekniker",
  "Matematiker",
  "Medicinsk ingenjör",
  "Mejeritekniker",
  "Mekanikkonstruktör",
  "Montör vid löpande band",
  "Motordesigner",
  "Mättekniker / Mätningstekniker",
  "Optotekniker/fibertekniker",
  "Planeringsarkitekt",
  "Processingenjör",
  "Processtekniker",
  "Produktionsingenjör",
  "Produktionsmedarbetare",
  "Produktutvecklare",
  "Projektingenjör",
  "Pyrotekniker",
  "Restaurangtekniker/storkökstekniker",
  "Robotutvecklare",
  "Rymddesigner",
  "Rymdingenjör",
  "Serviceingenjör",
  "Signalprojektör",
  "Sjöingenjör",
  "Solcellsmontör",
  "Solenergitekniker",
  "Svets- och robottekniker",
  "Svetsansvarig",
  "Systemförvaltare",
  "Tekniker",
  "Teknikinformatör",
  "Teknisk designer",
  "Teknisk illustratör",
  "Teknisk ritare",
  "Tele- och elektronikreparatör",
  "Testledare",
  "Textilingenjör",
  "Textiltekniker",
  "Trätekniker",
  "Tågtekniker",
  "Underhållsingenjör",
  "Uppfinnare",
  "Utrustningstekniker",
  "Utvecklingsingenjör",
  "Verktygsmakare",
  "Vindkraftprojektör",
  "Vindkrafttekniker",
  "Vinschoperatör",
  "VVS-konstruktör",
  "Värmetekniker",
];

export const swedishProffessions = [
  ...administrationEkonomi,
  ...byggAnlaggning,
  ...dataIt,
  ...djurensSjukvard,
  ...fordonTransport,
  ...forsaljningInkopMarknad,
  ...hantverk,
  ...hotellRestaurangTurism,
  ...halsaSjukvard,
  ...industri,
  ...installationDriftUnderhall,
  ...juridik,
  ...kroppsSkonhetsvard,
  ...kulturMediaDesign,
  ...naturbruk,
  ...naturvetenskapligtArbete,
  ...pedagogisktArbete,
  ...saneringRenhallning,
  ...socialtArbete,
  ...sakerhetsarbete,
  ...teknisktArbete,
];
